theme: jekyll-theme-minimal

permalink: pretty
exclude: ["README.md"]

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "labuzzetta on GitHub":
    - "//github.com/labuzzetta"
