theme: jekyll-theme-minimal
logo: 9397686.jpeg

permalink: pretty
exclude: ["README.md"]

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "labuzzetta on GitHub":
    - "//github.com/labuzzetta"
